### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by rohanchopra**

### CODE REVIEW

**Comment by jephillips** [comment]
Maybe add a link to the travis builds as well? 

https://travis-ci.org/javabrewery/brew-chat

**Comment by cjkennedyo** [comment]
After adding the travis link, I give my +1.

**Comment by arreche** [comment]
Do you know Markdown syntax? It's much more simple to format README files.

See
- https://guides.github.com/features/mastering-markdown/

**Comment by rohanchopra** [comment]
Added travis link. Stephen used HTML so I just went with that instead. (Markdown is used outside  of the list)

**Comment by arreche** [comment]
I vote for using a single format only and Markdown would be my choice :)

**Comment by arreche** [comment]
I have found this badge to track outdated dependencies.

[Dependency Status](https://www.versioneye.com/user/projects/5560400f634daa30fb001126)

Maybe It could be added to the readme too. What do you think?

**Comment by arreche** [comment]
# brew-chat

[Build Status](https://travis-ci.org/javabrewery/brew-chat) [Dependency Status](https://www.versioneye.com/user/projects/5560400f634daa30fb001126) [Install APK](https://community.testfairy.com/join/v9LITRNC)

A multi protocol chat application for devices running Android 4.1+

[Quickblox](http://quickblox.com) is being used for the backend so that we don't have to build our own backend, this might change in the future. We are also using [GreenRobot's eventbus](https://github.com/greenrobot/EventBus), and [Butterknife](https://github.com/JakeWharton/butterknife). See all dependencies in `brewchat/build.gradle` file.

## Quickstart
1. Download and install [Android Studio](http://developer.android.com/sdk/index.html)
2. Clone the project or a fork of it to your local development machine
3. Import the project into Android Studio
4. Click on Sync Project with Gradle files to download all the dependencies
5. Open the SDK manager to install the required Android SDK Tools and Android SDK Build-tools
6. Build the project

You will need to have git installed on your system and it must be definded as a PATH variable if you are using windows.

## Contributing
1. Familiarize with the application installing the [latest build](https://community.testfairy.com/join/v9LITRNC) and reiewing the [mockups](https://slack-files.com/T04DDGS6S-F04H6E7TR-c10f94e290)
2. [Fork this project](https://help.github.com/articles/fork-a-repo/) to your account
3. [Create a branch](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository) for the change you intend to make
4. Make your changes to your fork
5. [Send a pull request](https://help.github.com/articles/using-pull-requests/) from your forkâ€™s branch to our `master` branch.

## Services
- [Github](https://github.com/javabrewery/brew-chat) for project hosting and collaboration
- [Hangouts](https://hangoutsapi.talkgadget.google.com/hangouts/_/gy4efilvxipymnfskidvfuyzhea) for pair programming
- [Travis CI](https://travis-ci.org/javabrewery/brew-chat) for continuous integration
- [TestFairy](https://community.testfairy.com/join/v9LITRNC) to distribute betas
- [Trello](https://trello.com/b/L1Z2bkka/brew-chat) for project management
- [Slack](https://thejavabrewery.slack.com) for internal communication
- [Reddit](http://www.reddit.com/r/thejavabrewery) as community platform

**Comment by arreche** [comment]
What do you guys think about this redesign?

**Comment by jephillips** [comment]
+1

**Comment by cjkennedyo** [comment]
+1

**Pull request merged**
